name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_run:
    workflows:
      - bump
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: Build binaries
        run: |
          bun install
          bun run build

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BINARIES=$(find . -type f -name "vibedove-*")
          
          gh release create ${{ github.ref_name }} \
            --generate-notes \
            $BINARIES
