name: Bump and Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Bump version
        run: |
          bun pm version ${{ inputs.bump_type }}

      - name: Get new version
        id: ver
        run: |
          version=$(jq -r .version package.json)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Push changes and tags
        run: |
          git push
          git push --tags

      - name: Build binaries
        run: |
          bun install
          bun run build

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BINARIES=$(find . -type f -name "vibedove-*")
          tag="v${{ steps.ver.outputs.version }}"
          gh release create "$tag" \
            --generate-notes \
            $BINARIES
